version: '3'

services:
  web:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - backend

  db:
    container_name: db-backend
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: beautiful
      MYSQL_DATABASE: frampol_db
    ports:
      - "3307:3307"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend

networks:
    backend:

volumes:
    app:
    db:
