services:
  web:
    container_name: web-app
    build:
      context: ./app
      # dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - 6080:5000
    environment:
      FLASK_APP: ./app/app.py
    volumes:
      - .:/app
    networks:
      - backend

  db:
    container_name: db-backend
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: beautiful
      MYSQL_DATABASE: frampol_db
    ports:
      - 3307:3307
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend

networks:
    backend:

volumes:
    app:
    db:


