# Use the mariadb:latest image as the base image
FROM mariadb:latest

# Install MariaDB client
#RUN apt-get update && \
#    apt-get install -y mariadb-client && \
#    rm -rf /var/lib/apt/lists/*

# Expose port 3306 for MySQL connections
EXPOSE 3306
