# Use the MySQL 8.0 image as the base image
FROM mysql:8.0

# Expose port 3306 for MySQL connections
EXPOSE 3307


# Use the mariadb:latest image as the base image
# FROM mariadb:latest

# # Expose port 3306 for MySQL connections
# EXPOSE 3307
